"""
Unit tests for SupabaseClient using the deterministic DummyClient.

These tests validate the modern ingestion contract:

    • correct construction of NoteRecord payloads
    • embedding generation via the injected EmbeddingClient
    • deterministic embedding behavior
    • proper error handling for invalid inputs

The SupabaseClient no longer exposes compute_embedding() directly.
Embeddings are now generated through:

        client.embedding_client.generate(body)

Run from project root:
    pytest -q
"""

from typing import List
import pytest

from pke.supabase_client import SupabaseClient
from pke.types import NoteRecord
from tests.dummy_supabase import DummyClient  # Fully typed, reusable test double

# =====================================================================
# Test: Successful upsert with embedding generation
# =====================================================================


def test_upsert_note_with_embedding_returns_record_and_embedding_length() -> None:
    """
    Validates that SupabaseClient.upsert_note_with_embedding:

        • returns a list containing one NoteRecord
        • preserves title, body, and metadata fields
        • attaches a 1536‑dimensional embedding vector generated by
          the client's embedding_client

    This test uses DummyClient to avoid real Supabase calls.
    """

    client = SupabaseClient(client=DummyClient())

    title = "Unit Test"
    body = "unit test body"
    metadata = {"test": True}

    # Generate embedding exactly as the orchestrator would.
    embedding = client.embedding_client.generate(body)

    # Perform the upsert using the modern signature.
    res: List[NoteRecord] = client.upsert_note_with_embedding(
        id="note-123",
        title=title,
        body=body,
        metadata=metadata,
        notebook_id=None,
        embedding=embedding,
    )

    # Validate structure
    assert isinstance(res, list)
    assert len(res) == 1

    rec = res[0]

    # Field preservation
    assert rec["title"] == title
    assert rec["body"] == body
    assert rec["metadata"] == metadata

    # Embedding validation
    emb = rec.get("embedding")
    assert emb is not None
    assert isinstance(emb, list)
    assert len(emb) == 1536


# =====================================================================
# Test: Embedding determinism
# =====================================================================


def test_embedding_generation_is_deterministic() -> None:
    """
    Ensures the deterministic embedding provider behaves as expected:

        • same input → identical vectors
        • different input → different vectors

    This validates the behavior of the deterministic EmbeddingClient
    used in tests and dry‑run mode.
    """

    client = SupabaseClient(client=DummyClient())

    a = client.embedding_client.generate("same text")
    b = client.embedding_client.generate("same text")
    c = client.embedding_client.generate("different text")

    assert a == b, "Embedding generation must be deterministic for identical input"
    assert a != c, "Different inputs must produce different embeddings"


# =====================================================================
# Test: Error handling
# =====================================================================


def test_upsert_note_with_embedding_raises_on_empty_body() -> None:
    """
    Ensures that calling upsert_note_with_embedding with an empty body
    raises ValueError.
    """

    client = SupabaseClient(client=DummyClient())

    with pytest.raises(ValueError, match="body must be provided"):
        client.upsert_note_with_embedding(
            id="x",
            title="Missing Body",
            body="",
            metadata={},
            notebook_id=None,
            embedding=[0.0] * 1536,
        )


def test_upsert_note_with_embedding_raises_if_client_is_none() -> None:
    """
    Ensures that calling upsert_note_with_embedding without a Supabase client
    raises RuntimeError in real mode.
    """

    client = SupabaseClient(client=None)

    with pytest.raises(RuntimeError, match="No client provided to SupabaseClient"):
        client.upsert_note_with_embedding(
            id="x",
            title="No Client",
            body="test body",
            metadata={},
            notebook_id=None,
            embedding=[0.0] * 1536,
        )
