-- =============================================================================
-- scripts/add_match_functions.sql
--
-- Registers pgvector similarity search functions for the PKE retrieval API.
--
-- These functions are called via Supabase RPC from pke/retrieval/retriever.py.
-- They implement the hybrid retrieval strategy:
--
--     match_chunks  — primary search: chunk-level similarity
--     match_notes   — fallback search: note-level similarity for notes
--                     that have no chunk-level embeddings
--
-- WHY TWO FUNCTIONS:
--     Notes above the chunking threshold (1000 chars) are split into chunks
--     and each chunk gets its own embedding. These chunks are more precise
--     retrieval targets than the whole note because they represent a single
--     dated entry or section rather than months of mixed content.
--
--     Notes below the threshold are not chunked — their note-level embedding
--     is sufficient. match_notes returns only these smaller notes, ensuring
--     chunk results and note-level fallback results never overlap.
--
-- DISTANCE METRIC:
--     Both functions use cosine distance (<=> operator from pgvector).
--     Cosine distance measures the angle between two vectors — it captures
--     semantic similarity regardless of vector magnitude, which makes it
--     the correct choice for comparing text embeddings.
--
--     Raw cosine distance is in range [0, 2] where 0 = identical.
--     We convert to similarity with (1 - distance), giving range [-1, 1]
--     where 1 = identical. The retriever ranks results by this score
--     descending so the most relevant results surface first.
--
-- IDEMPOTENCY:
--     Both functions use CREATE OR REPLACE, so this script is safe to
--     re-run. Re-running will update the function definition in place
--     without dropping dependent objects.
--
-- USAGE:
--     Run once in the Supabase SQL editor to register the functions.
--     Re-run any time the function signatures or logic need to change.
--     Functions are called from Python via:
--         client.rpc("match_chunks", {...}).execute()
--         client.rpc("match_notes",  {...}).execute()
-- =============================================================================


-- -----------------------------------------------------------------------------
-- match_chunks
--
-- Primary retrieval function. Searches the chunks table for the most
-- semantically similar chunks to the query embedding.
--
-- Each chunk represents a single dated entry or section of a note. Chunk-level
-- search is more precise than note-level search because long notes containing
-- months of content are split into individually retrievable units.
--
-- Parameters:
--     query_embedding  — the 1536-dimensional embedding of the user's query,
--                        generated by OpenAI text-embedding-3-small at
--                        request time in pke/retrieval/retriever.py
--
--     match_count      — maximum number of results to return. The retriever
--                        typically requests 10 chunk candidates and then
--                        merges and re-ranks with note-level fallback results
--                        before returning the final top N to the caller.
--
--     filter_notebook  — optional notebook title filter. When provided, only
--                        chunks belonging to notes in that notebook are
--                        returned. When NULL, all notebooks are searched.
--
-- Returns one row per matching chunk with full provenance metadata:
--     chunk_id         — UUID of the chunk row (for future deep linking)
--     note_id          — UUID of the parent note (for Obsidian deep linking)
--     note_title       — human-readable note title for display in insight panel
--     notebook         — notebook name for context and optional filtering
--     chunk_text       — the raw passage text (never summarized)
--     chunk_index      — position of this chunk within its parent note
--     section_title    — section heading if detected during chunking, else NULL
--     entry_timestamp  — date of entry: explicit, calculated, or NULL
--                        format: "2015-09-08" | "calculated: 2014-08-04" | NULL
--     resource_ids     — array of image/audio resource IDs embedded in chunk
--     similarity       — cosine similarity score in range [-1, 1],
--                        higher = more relevant
--
-- WHY JOIN TO notebooks:
--     The notes table stores notebook_id (a UUID foreign key) not the
--     notebook title. Joining to notebooks resolves the human-readable
--     title needed by the insight panel and the optional title-based filter.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION match_chunks(
    query_embedding  vector(1536),
    match_count      int,
    filter_notebook  text DEFAULT NULL
)
RETURNS TABLE (
    chunk_id         uuid,
    note_id          uuid,
    note_title       text,
    notebook         text,
    chunk_text       text,
    chunk_index      int,
    section_title    text,
    entry_timestamp  text,
    resource_ids     text[],
    similarity       float
)
LANGUAGE sql STABLE
AS $$
    SELECT
        c.id                                   AS chunk_id,
        c.note_id                              AS note_id,
        n.title                                AS note_title,
        nb.title                               AS notebook,
        c.chunk_text                           AS chunk_text,
        c.chunk_index                          AS chunk_index,
        c.section_title                        AS section_title,
        c.entry_timestamp                      AS entry_timestamp,
        c.resource_ids                         AS resource_ids,
        1 - (c.embedding <=> query_embedding)  AS similarity
    FROM   chunks    c
    JOIN   notes     n  ON c.note_id     = n.id
    JOIN   notebooks nb ON n.notebook_id = nb.id
    WHERE  c.embedding IS NOT NULL
    AND   (filter_notebook IS NULL OR nb.title = filter_notebook)
    ORDER BY c.embedding <=> query_embedding
    LIMIT  match_count;
$$;


-- -----------------------------------------------------------------------------
-- match_notes
--
-- Fallback retrieval function. Searches the notes table for semantically
-- similar notes that have NO chunk-level embeddings.
--
-- WHY THIS EXISTS:
--     Notes below the chunking threshold (1000 chars) are not split into
--     chunks. Their note-level embedding is sufficient for retrieval.
--     Without this fallback, short notes would be invisible to the
--     retrieval API entirely.
--
--     The NOT EXISTS subquery ensures this function only returns notes
--     that have no chunk embeddings — preventing the same content from
--     appearing in both chunk results and note-level fallback results.
--     This is the hybrid retrieval contract enforced at the database level.
--
-- Parameters:
--     query_embedding  — the 1536-dimensional query embedding, same as
--                        match_chunks. Generated once per request in
--                        pke/retrieval/retriever.py and passed to both
--                        functions.
--
--     match_count      — maximum number of fallback results to return.
--                        Typically smaller than chunk match_count since
--                        note-level results are lower precision.
--
--     filter_notebook  — optional notebook title filter, same behavior
--                        as match_chunks.
--
-- Returns one row per matching note:
--     note_id          — UUID of the note (for Obsidian deep linking)
--     note_title       — human-readable note title
--     notebook         — notebook name
--     note_text        — full note body (the matched passage)
--     similarity       — cosine similarity score, higher = more relevant
--
-- WHY FEWER RETURN COLUMNS THAN match_chunks:
--     Note-level results have no chunk metadata (chunk_index, section_title,
--     entry_timestamp, resource_ids) because the note was never chunked.
--     The retriever maps both result types to QueryResult, using None
--     for chunk-specific fields when result_type is "note".
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION match_notes(
    query_embedding  vector(1536),
    match_count      int,
    filter_notebook  text DEFAULT NULL
)
RETURNS TABLE (
    note_id          uuid,
    note_title       text,
    notebook         text,
    note_text        text,
    similarity       float
)
LANGUAGE sql STABLE
AS $$
    SELECT
        n.id                                   AS note_id,
        n.title                                AS note_title,
        nb.title                               AS notebook,
        n.body                                 AS note_text,
        1 - (n.embedding <=> query_embedding)  AS similarity
    FROM   notes     n
    JOIN   notebooks nb ON n.notebook_id = nb.id
    WHERE  n.embedding IS NOT NULL
    AND    NOT EXISTS (
               SELECT 1
               FROM   chunks c
               WHERE  c.note_id = n.id
               AND    c.embedding IS NOT NULL
           )
    AND   (filter_notebook IS NULL OR nb.title = filter_notebook)
    ORDER BY n.embedding <=> query_embedding
    LIMIT  match_count;
$$;