-- =============================================================================
-- scripts/add_match_functions.sql
--
-- Registers pgvector similarity search functions for the PKE retrieval API.
--
-- These functions are called via Supabase RPC from pke/retrieval/retriever.py.
-- They implement the hybrid retrieval strategy:
--
--     match_chunks  — primary search: chunk-level similarity
--     match_notes   — fallback search: note-level similarity for notes
--                     that have no chunk-level embeddings
--
-- WHY TWO FUNCTIONS:
--     Notes above the chunking threshold (1000 chars) are split into chunks
--     and each chunk gets its own embedding. These chunks are more precise
--     retrieval targets than the whole note because they represent a single
--     dated entry or section rather than months of mixed content.
--
--     Notes below the threshold are not chunked — their note-level embedding
--     is sufficient. match_notes returns only these smaller notes, ensuring
--     chunk results and note-level fallback results never overlap.
--
-- DISTANCE METRIC:
--     Both functions use cosine distance (<=> operator from pgvector).
--     Cosine distance measures the angle between two vectors — it captures
--     semantic similarity regardless of vector magnitude, which makes it
--     the correct choice for comparing text embeddings.
--
--     Raw cosine distance is in range [0, 2] where 0 = identical.
--     We convert to similarity with (1 - distance), giving range [-1, 1]
--     where 1 = identical. The retriever ranks results by this score
--     descending so the most relevant results surface first.
--
-- IDEMPOTENCY:
--     match_notes uses CREATE OR REPLACE and is safe to re-run in place.
--
--     match_chunks cannot use CREATE OR REPLACE alone when its return type
--     changes — Postgres requires DROP FUNCTION first in that case.
--     The canonical drop + create sequence is:
--
--         DROP FUNCTION match_chunks(vector, integer, text, integer);
--         CREATE OR REPLACE FUNCTION match_chunks(...) ...
--
--     This is safe — no table data is affected. The function definition
--     is recreated immediately in the same statement batch.
--
-- USAGE:
--     Run once in the Supabase SQL editor to register the functions.
--     Re-run any time the function signatures or logic need to change.
--     Functions are called from Python via:
--         client.rpc("match_chunks", {...}).execute()
--         client.rpc("match_notes",  {...}).execute()
-- =============================================================================


-- -----------------------------------------------------------------------------
-- match_chunks
--
-- Primary retrieval function. Searches the chunks table for the most
-- semantically similar chunks to the query embedding.
--
-- Supports multiple source types in the chunks table:
--     source_type = 'joplin'   — joined to notes + notebooks for title/notebook
--     source_type = 'imessage' — joined to imessage_bursts for thread_name;
--                                notebook returned as 'iMessage'
--
-- All joins are LEFT JOINs so rows from either source type are returned
-- correctly. COALESCE selects the appropriate value per source type.
--
-- Parameters:
--     query_embedding  — the 1536-dimensional embedding of the user's query,
--                        generated by OpenAI text-embedding-3-small at
--                        request time in pke/retrieval/retriever.py
--
--     match_count      — maximum number of results to return. The retriever
--                        typically requests 10 chunk candidates and then
--                        merges and re-ranks with note-level fallback results
--                        before returning the final top N to the caller.
--
--     filter_notebook  — optional notebook title filter. When provided, only
--                        chunks belonging to notes in that notebook are
--                        returned. Applies to Joplin chunks only — iMessage
--                        rows have NULL note_id and are unaffected by this
--                        filter. When NULL, all sources are searched.
--
--     max_privacy_tier — maximum privacy tier to include. Default 2 excludes
--                        bilateral threads (tier 3). Pass 3 to include them.
--
-- Returns one row per matching chunk with full provenance metadata:
--     id               — UUID of the chunk row
--     note_id          — UUID of the parent note (Joplin rows); NULL for iMessage
--     chunk_index      — position of this chunk within its parent note
--     chunk_text       — the raw passage text (never summarized)
--     similarity       — cosine similarity score in range [-1, 1]
--     section_title    — section heading if detected during chunking, else NULL
--     entry_timestamp  — date of entry: explicit, calculated, or NULL
--     resource_ids     — array of image/audio resource IDs embedded in chunk
--     result_type      — always 'chunk'
--     source_type      — 'joplin' | 'imessage'
--     source_id        — imessage_bursts.id for iMessage rows; NULL for Joplin
--     privacy_tier     — 2 (group/personal) | 3 (bilateral)
--     note_title       — note title (Joplin) | thread name (iMessage)
--     notebook         — notebook name (Joplin) | 'iMessage'
--
-- ADD NEW SOURCE TYPES HERE:
--     When a new source is added (e.g. email), add a LEFT JOIN to the
--     relevant table and extend the COALESCE chain for note_title and
--     notebook. The retriever requires both fields on every row.
-- -----------------------------------------------------------------------------
DROP FUNCTION IF EXISTS match_chunks(vector, integer, text, integer);

CREATE OR REPLACE FUNCTION match_chunks(
    query_embedding     vector(1536),
    match_count         INT DEFAULT 5,
    filter_notebook     TEXT DEFAULT NULL,
    max_privacy_tier    INT DEFAULT 2
)
RETURNS TABLE (
    id              UUID,
    note_id         UUID,
    chunk_index     INTEGER,
    chunk_text      TEXT,
    similarity      FLOAT,
    section_title   TEXT,
    entry_timestamp TEXT,
    resource_ids    TEXT[],
    result_type     TEXT,
    source_type     TEXT,
    source_id       TEXT,
    privacy_tier    INTEGER,
    note_title      TEXT,
    notebook        TEXT
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        c.id,
        c.note_id,
        c.chunk_index,
        c.chunk_text,
        1 - (c.embedding <=> query_embedding) AS similarity,
        c.section_title,
        c.entry_timestamp,
        c.resource_ids,
        'chunk'::TEXT                             AS result_type,
        c.source_type,
        c.source_id,
        c.privacy_tier,
        COALESCE(n.title,   b.thread_name)        AS note_title,
        COALESCE(nb.title,  'iMessage'::TEXT)     AS notebook
    FROM chunks c
    LEFT JOIN notes           n  ON c.note_id  = n.id
    LEFT JOIN notebooks       nb ON n.notebook_id = nb.id
    LEFT JOIN imessage_bursts b  ON c.source_id = b.id
    WHERE
        c.embedding IS NOT NULL
        AND c.privacy_tier <= max_privacy_tier
        AND (
            filter_notebook IS NULL
            OR (
                c.note_id IS NOT NULL
                AND nb.title = filter_notebook
            )
        )
    ORDER BY c.embedding <=> query_embedding
    LIMIT match_count;
END;
$$;

COMMENT ON FUNCTION match_chunks IS
    'Semantic search across all chunks (Joplin + iMessage + future sources). '
    'Returns note_title and notebook for every row regardless of source type. '
    'Joplin rows: joined to notes + notebooks. '
    'iMessage rows: thread_name as note_title, ''iMessage'' as notebook. '
    'max_privacy_tier=2 default excludes bilateral threads (tier 3).';


-- -----------------------------------------------------------------------------
-- match_notes
--
-- Fallback retrieval function. Searches the notes table for semantically
-- similar notes that have NO chunk-level embeddings.
--
-- WHY THIS EXISTS:
--     Notes below the chunking threshold (1000 chars) are not split into
--     chunks. Their note-level embedding is sufficient for retrieval.
--     Without this fallback, short notes would be invisible to the
--     retrieval API entirely.
--
--     The NOT EXISTS subquery ensures this function only returns notes
--     that have no chunk embeddings — preventing the same content from
--     appearing in both chunk results and note-level fallback results.
--     This is the hybrid retrieval contract enforced at the database level.
--
-- Parameters:
--     query_embedding  — the 1536-dimensional query embedding, same as
--                        match_chunks. Generated once per request in
--                        pke/retrieval/retriever.py and passed to both
--                        functions.
--
--     match_count      — maximum number of fallback results to return.
--                        Typically smaller than chunk match_count since
--                        note-level results are lower precision.
--
--     filter_notebook  — optional notebook title filter, same behavior
--                        as match_chunks.
--
-- Returns one row per matching note:
--     note_id          — UUID of the note (for Obsidian deep linking)
--     note_title       — human-readable note title
--     notebook         — notebook name
--     note_text        — full note body (the matched passage)
--     similarity       — cosine similarity score, higher = more relevant
--
-- WHY FEWER RETURN COLUMNS THAN match_chunks:
--     Note-level results have no chunk metadata (chunk_index, section_title,
--     entry_timestamp, resource_ids) because the note was never chunked.
--     The retriever maps both result types to QueryResult, using None
--     for chunk-specific fields when result_type is "note".
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION match_notes(
    query_embedding  vector(1536),
    match_count      int,
    filter_notebook  text DEFAULT NULL
)
RETURNS TABLE (
    note_id          uuid,
    note_title       text,
    notebook         text,
    note_text        text,
    similarity       float
)
LANGUAGE sql STABLE
AS $$
    SELECT
        n.id                                   AS note_id,
        n.title                                AS note_title,
        nb.title                               AS notebook,
        n.body                                 AS note_text,
        1 - (n.embedding <=> query_embedding)  AS similarity
    FROM   notes     n
    JOIN   notebooks nb ON n.notebook_id = nb.id
    WHERE  n.embedding IS NOT NULL
    AND    NOT EXISTS (
               SELECT 1
               FROM   chunks c
               WHERE  c.note_id = n.id
               AND    c.embedding IS NOT NULL
           )
    AND   (filter_notebook IS NULL OR nb.title = filter_notebook)
    ORDER BY n.embedding <=> query_embedding
    LIMIT  match_count;
$$;
